### ISSUE TITLE
关于同样的文件计算出的hash值不一样的疑问

### ISSUE THREAD

**Issue by umarurize** [Jissee/JarsAuth#1]
因为特殊原因，给玩家准备了两个客户端。

我只想检测mods文件夹和resourcepacks文件夹，设定如下inclusions = ["mods/*”,"resourcepacks"]，exclusion=[]。

但是在不同客户端，同样的mod和材质包计算出的hash却不一样，导致一部分玩家进不去。不知道是我设定错误，还是什么原因。

**Comment by Jissee** [comment]
问一下“两个客户端”是什么意思？你确定两个客户端对应的目录下的文件完全一样吗？
也有可能在不同平台如mac和windows下计算出的hash值不同，如果有不同的话，在服务端配置里都加上就行

**Comment by umarurize** [comment]
两个客户端目录不完全一样，但所用mod和resourcepack 完全一样，也是在同一个电脑上算的hash

原来可以检测多个hash嘛，那太好了！

还有1个问题，大佬，就是加入游戏的速度会变慢，我估计是在核对文件，不知道这里能不能优化一下

总之，很好的mod

**Comment by Jissee** [comment]
方便的话提供一下两个客户端的文件目录结构以及具体的配置文件，这将会有助于我检查问题
加载速度变慢是没办法的，毕竟要检测数据量那么大的文件
我也会继续优化代码，提高运行效率

**Comment by umarurize** [comment]
[report.zip](https://github.com/Jissee/JarsAuth/files/12144798/report.zip)
客户端1 和 客户端2 只是内置的更新站不同，一个部署的第三方更新站mcpatch ，一个是hmcl自带的更新站。

**Comment by Jissee** [comment]
抱歉，根据目前信息我目前没能发现问题所在，能否提供一下两个客户端的具体下载方式

**Comment by umarurize** [comment]
需要晚点发到您邮箱

**Comment by Jissee** [comment]
你好，经过我连夜排查问题，目前认为原因如下：你可能安装了自动汉化更新模组（https://www.mcmod.cn/class/1188.html），这个模组会在每次启动时下载文件到材质包文件夹，导致每次启动时的哈希签名都不同，现在建议你升级到最新版，并且在客户端配置中排除上述文件。
