### ISSUE TITLE
Support for utf8 encoding?

### ISSUE THREAD

**Issue by LinRanAstra** [Jissee/JarsAuth#13]
Very good module, but he does not support Chinese!
I hope the file can support utf8 encoding, so that it can edit and output Chinese correctly!

**Comment by Jissee** [comment]
请问是哪一部分输出有误，以便复现与修复问题

**Comment by LinRanAstra** [comment]
在mcsm面板上，编辑文件时会出现很多问号,在本地经过测试后确认为编码所造成的错误,它默认为 gbk 编码
![image](https://github.com/Jissee/JarsAuth/assets/99112592/5108ce40-2d53-4cd5-963f-5a9372ced742)

**Comment by Jissee** [comment]
请尝试5.0，已经把描述和配置分开。5.0已经在 Modrinth 上发布，mod百科由于需要审核更新较慢

**Comment by Jissee** [comment]
mod百科已经更新，请查看使用及配置方式，如有问题欢迎提新的问题
