### ISSUE TITLE
哈希值无法改变

### ISSUE THREAD

**Issue by MILK2679** [Jissee/JarsAuth#2]
游戏版本1.16.5-Forge_36.2.39
客户端是新装的，没有版本独立

你好，我的客户端配置文件是这样写的，但我怎么修改删除我目录内的mod，我在单人游戏里生成的哈希值永远是一样，就算配置文件内的inclusions = ["mods/*"]写成inclusions = ["mods/xxxx.jar"]也会生成同一个哈希值，但修改为inclusions = ["其他目录比如/*config"]他就会改变

inclusions = ["mods/*"]

exclusions = ["resourcepacks/Minecraft-Mod-Language-Modpack-Converted-1.16.5.zip", "examplefile.log"]

服务端内边就不用说了，怎么更改mod都让进

**Comment by Jissee** [comment]
你是否使用了模组的最新版，就是20230726更新之后的那个？还有能否提供一下当前的模组列表？

**Comment by MILK2679** [comment]
是最新版，CurseForge上下载的，似乎不像是mod冲突，mod只有JarsAuth和一个简单的RandomTitle，我删除RandomTitle和保留他，我生成的哈希都是一样的

**Comment by MILK2679** [comment]
> 你是否使用了模组的最新版，就是20230726更新之后的那个？还有能否提供一下当前的模组列表？
是最新版，CurseForge上下载的，似乎不像是mod冲突，mod只有JarsAuth和一个简单的RandomTitle，我删除RandomTitle和保留他，我生成的哈希都是一样的

**Comment by MILK2679** [comment]
另外还有一个现象提一嘴，客户端服务端配置的中文注释部分我用notepad打开是乱码，但似乎用系统记事本导出ansi编码，大部分中文就正常了

**Comment by MILK2679** [comment]
复现起来很容易，你可以试试

**Comment by Jissee** [comment]
好的，问题已经确认，我会进行修改

**Comment by Jissee** [comment]
你好，我想再问一下，你是如何获取到客户端哈希值的？可能是由于Mojang官方的文件变化，我当前在开发环境下无法执行命令了。但是修复这个问题后我获取到的哈希值仍然是可以随着文件变化而变化的。

**Comment by MILK2679** [comment]
我用指令获取到的，只不过指令没给我任何反馈回应，只是我粘贴板多了个哈希值，不到这种现象正常不

**Comment by Jissee** [comment]
> 我用指令获取到的，只不过指令没给我任何反馈回应，只是我粘贴板多了个哈希值，不到这种现象正常不

这和我的开发环境下的情况一样，应该是Mojang文件变化导致（估计1.16.5就是官方的实验版本，有变化就先在这个版本尝试，之前多人模式强制正版也是在这个版本下进行的，导致模组开发无法使用1.16.5调试服务器，因为模组调试是离线的），现在新的修复版本已经上传CurseForge，请再次尝试是否存仍然在上述问题。

**Comment by MILK2679** [comment]
1.16.5好像从CurseForge上没了（挠头

**Comment by Jissee** [comment]
不知道为什么新文件没过审，已经很长时间了

> 1.16.5好像从CurseForge上没了（挠头

**Comment by MILK2679** [comment]
题外话，请问你有空吗，我想找你定制些mod，可能是长期的

**Comment by Jissee** [comment]
> 题外话，请问你有空吗，我想找你定制些mod，可能是长期的

看情况，我下半年大三了，有关其他话题希望能通过邮件（mailto:2431740933@qq.com）等方式私聊

**Comment by Jissee** [comment]
最新版已经通过github release发布

**Comment by MILK2679** [comment]
收到

**Comment by MILK2679** [comment]
问题仍然会有，我加你qq了

**Comment by Jissee** [comment]
问题已经解决
