### ISSUE TITLE
更高版本

### ISSUE THREAD

**Issue by KaedeVicky** [Jissee/JarsAuth#5]
我在尝试将4.0版本mod用于1.20.2版本时，服务端可以正常加载此mod，但是客户端一直处于初始化阶段崩溃并提示：Could not execute entrypoint stage 'main' due to errors, provided by 'fabric-networking-api-v1'

请问作者是否有解决方案或者更新该mod到更高版本的意愿？
希望作者能回复，谢谢。

**Comment by Jissee** [comment]
之前直接用邮件回复了，不知道你有没有看到：）

**Comment by KaedeVicky** [comment]
作者可能搞错了，这边是第一次提问，没收到邮件。我的邮箱是kaedevicky@gmail.com

**Comment by Jissee** [comment]
是这样的，每一个 issue 都会给作者发邮件的，我收到后用邮件里的回复功能回复你了，但是由于某些原因你没有收到，那我就重新说明一下吧：1.20.3 马上要推出了，作者精力有限会跳过 1.20.2 版本。另外请检查一下有没有使用 “-javaagent” 参数，此模组不能在使用此参数的情况下启动。

**Comment by KaedeVicky** [comment]
好的，谢谢作者回复！
