### ISSUE TITLE
1.20.1的4.4版本，客户端签名进入服务器后就会变化，导致无法进服

### ISSUE THREAD

**Issue by Star-Jirachi** [Jissee/JarsAuth#8]
严格按照说明操作，即：
1.服务器控制台输入jarsauth record
2.客户端进入，控制台看到“Client details reloaded”时退出
3.控制台再次输入jarsauth record
4.控制台输入jarsauth reload
5.客户端进入
但进行第五步时，就无法进入服务器了，提示客户端签名与服务端记录不一致。
重复了6遍以上操作，都是这样。
我查看了生成的6个acc-x.json文件，发现每个文件的"${quickPlayPath}"值都不一样，不知道是不是这个原因导致的问题？
我每次操作使用的是同一个客户端，并且没有重启过客户端，只是不断进出服务器，应该是每次进入服务器时客户端的"${quickPlayPath}"都会改变，导致服务器误报。
为了验证，我试验了一下。上面的说明操作，如果我在第二步时看到“Client details reloaded”后不退出，然后客户端输入jarsauth record和jarsauth reload，就不会被踢出，但是退出服务器后再进就提示签名不一致了。
所以大概率是客户端进入服务器，签名就会改变？

**Comment by Jissee** [comment]
有可能是你把 “${quickPlayPath}” 纳入了检测文件的列表，该文件文件属于每次启动就会改变的文件，从[更新日志](https://minecraft.wiki/w/Java_Edition_23w14a)来看，它需要记录`lastPlayedTime`，即上一次进入服务器的时间，这个在每次进入服务器后就会改变。这种文件就很难检测，如果按照文件名排除就容易在游戏中将其替换成同名文件从而绕过检查。因此建议还是不要检测这类文件。如果确有需要，我也考虑在下一版本中重新加入更加完善的“排除”机制。

**Comment by Star-Jirachi** [comment]
> 有可能是你把 “${quickPlayPath}” 纳入了检测文件的列表，该文件文件属于每次启动就会改变的文件，从[更新日志](https://minecraft.wiki/w/Java_Edition_23w14a)来看，它需要记录`lastPlayedTime`，即上一次进入服务器的时间，这个在每次进入服务器后就会改变。这种文件就很难检测，如果按照文件名排除就容易在游戏中将其替换成同名文件从而绕过检查。因此建议还是不要检测这类文件。如果确有需要，我也考虑在下一版本中重新加入更加完善的“排除”机制。

那应该不是这个原因。但是我应该并没有将 “${quickPlayPath}” 纳入检测文件的列表，因为“jarsauth-profile.json”文件我并没有修改过，是默认值。
请问还有什么原因会导致这个我说的这个问题呢？
就是进服会提示客户端签名与服务端记录不一致。

**Comment by Jissee** [comment]
能否提供以下acc-x.json文件，以及更加详细的环境配置信息，如服务端类型、版本、整合包信息等？

**Comment by Star-Jirachi** [comment]
[acc-6.json](https://github.com/Jissee/JarsAuth/files/13427440/acc-6.json)

**Comment by Star-Jirachi** [comment]
> 能否提供以下acc-x.json文件，以及更加详细的环境配置信息，如服务端类型、版本、整合包信息等？

服务端是1.20.1 mohist
我等会儿再测试下只加Jarsauth 4.4行不行

**Comment by Jissee** [comment]
请你再留意一下，是不是真的有一个文件叫`${quickPlayPath}`，以及其他文件或文件夹有没有发生变动

**Comment by Star-Jirachi** [comment]
> 请你再留意一下，是不是真的有一个文件叫`${quickPlayPath}`，以及其他文件或文件夹有没有发生变动

你误会我意思了，没有叫${quickPlayPath}的文件或者文件夹。我指的是打开acc-x.json文件，acc-x.json文件的开头有个值是${quickPlayPath}，不是说有叫${quickPlayPath}的文件。

**Comment by Star-Jirachi** [comment]
我有过会儿测试下服务端只加Jarsauth有没有问题，也可能是我整合包有问题导致服务器误报。

**Comment by Star-Jirachi** [comment]
唉，问题有点麻烦了，只加jarsauth可以正常验证。应该是我整合包的问题，我明天排查一下吧

**Comment by Star-Jirachi** [comment]
> 请你再留意一下，是不是真的有一个文件叫`${quickPlayPath}`，以及其他文件或文件夹有没有发生变动

经过反复测试，发现是检测的mod名中不能含有中文名。我有的mod名含中文，导致了服务器误报。

**Comment by Star-Jirachi** [comment]
测试了一下，如果客户端作弊，服务器提示信息的中文部分是乱码的，并且有时配置文件jarsauth-profile.json里面的中文部分也会全部乱码。
估计是mod中文识别部分有点问题？所以导致了识别文件内有中文会报错。

**Comment by Jissee** [comment]
我目前也找不出是什么原因，尤其是“有时会乱码”真的很奇怪，我这边测试中文编码一直都是没问题的，在win和mac下用了 
mohist、arclight、forge 都没问题。π_π

**Comment by Star-Jirachi** [comment]
> 我目前也找不出是什么原因，尤其是“有时会乱码”真的很奇怪，我这边测试中文编码一直都是没问题的，在win和mac下用了 mohist、arclight、forge 都没问题。π_π

好吧，问题也不大，乱码对实际功能也没影响，并且我把检测文件名都改为英文就行了，mod完全可以正常运行。如果之后我发现原因了再告诉你吧。
