### ISSUE TITLE
bukkit兼容

### ISSUE THREAD

**Issue by LinRanAstra** [Jissee/JarsAuth#9]
可以让这个mod兼容bukkit插件吗，我想在插件服中使用它，我还没有在市面上找到相关好用的同类型插件

**Comment by Jissee** [comment]
这种模组是需要同时修改服务端和客户端的，`bukkit` `spigot`等插件端只能修改服务端行为，从原理上来说是无法实现的`ToT`，如果确有需要可以考虑使用混合端，如`Mohist` `Arclight`等
